import { FormEvent, useContext } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { MdOutlineDarkMode, MdOutlineLightMode, MdSearch } from 'react-icons/md';
import { useBreakpoint } from '@react-jopau/hooks';
import {
  Button,
  Checkbox,
  Container,
  Grid,
  Header,
  Heading,
  Input,
  Radio,
  Select,
  Space,
  Switch,
  Textarea,
  ThemeContext
} from '@react-jopau/components';

const inter = Inter({ subsets: ['latin'] });

const Logo = () => (
  <div className="flex gap-4 text-text h-[20px]">
    <Image src="/next.svg" alt="Next.js Logo" width={110} height={37} />
    <Image src="/thirteen.svg" alt="13" width={30} height={31} />
  </div>
);

const Home = () => {
  const { darkMode, onToggle } = useContext(ThemeContext);
  const breakpoint = useBreakpoint();

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header logo={<Logo />} maxWidth="lg">
          <Grid align="center" gap={1} className="!w-fit">
            <Grid.Item>
              <Input
                className="max-sm:hidden"
                variant="bordered"
                placeholder="Search"
                hotKey="meta+k"
              />
            </Grid.Item>
            <Grid.Item className="sm:hidden">
              <Button color="primary" variant="flat" icon={<MdSearch />} />
            </Grid.Item>
            <Grid.Item>
              <Button
                variant="flat"
                color={!darkMode ? 'light' : 'dark'}
                icon={darkMode ? <MdOutlineLightMode /> : <MdOutlineDarkMode />}
                onClick={onToggle}
              />
            </Grid.Item>
          </Grid>
        </Header>
      </header>

      <main>
        <Container maxWidth="lg" centered className="py-14">
          <h4 className={inter.className}>Current breakpoint: {breakpoint.key}</h4>

          <Space y={1} />

          <Heading as="h4" color="primary">
            Form
          </Heading>

          <Space y={0.5} />

          <form onSubmit={handleSubmit} className="flex flex-col gap-8 w-[400px] max-w-[100%]">
            <Input label="Name" placeholder="John Doe" fullWidth />
            <Select size="sm" label="Country" fullWidth>
              <Select.Option value="FR">France</Select.Option>
              <Select.Option value="ES">Spain</Select.Option>
              <Select.Option value="IT">Italy</Select.Option>
              <Select.Option value="DE">Germany</Select.Option>
            </Select>
            <Checkbox.Group size="sm" orientation="horizontal" label="Preferences">
              <Checkbox value="football">Football</Checkbox>
              <Checkbox value="food">Food</Checkbox>
              <Checkbox value="other">Other</Checkbox>
            </Checkbox.Group>
            <Radio.Group
              size="sm"
              orientation="horizontal"
              label="Contact me via"
              defaultValue="email">
              <Radio value="email">Email</Radio>
              <Radio value="phone">Phone</Radio>
              <Radio value="not">Dont contact me</Radio>
            </Radio.Group>
            <Textarea
              label="Message"
              minRows={10}
              maxRows={15}
              placeholder="Your message"
              fullWidth
            />
            <Switch size="xs">Subscribe to newsletter</Switch>
            <Button type="submit" color="secondary">
              Contact me
            </Button>
          </form>
        </Container>
      </main>
    </>
  );
};

export default Home;
