/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./packages/**/*.{js,jsx,ts,tsx,mdx}', './.storybook/**/*.{js,jsx,ts,tsx,mdx}'],
  theme: {
    colors: {
      black: 'var(--rjopau-colors-black)',
      white: 'var(--rjopau-colors-white)',
      accent: 'var(--rjopau-colors-accent)',
      primary: {
        DEFAULT: 'var(--rjopau-colors-primary500)',
        100: 'var(--rjopau-colors-primary100)',
        200: 'var(--rjopau-colors-primary200)',
        300: 'var(--rjopau-colors-primary300)',
        400: 'var(--rjopau-colors-primary400)',
        500: 'var(--rjopau-colors-primary500)',
        600: 'var(--rjopau-colors-primary600)',
        700: 'var(--rjopau-colors-primary700)',
        800: 'var(--rjopau-colors-primary800)',
        900: 'var(--rjopau-colors-primary900)',
        text: 'var(--rjopau-colors-primaryText)'
      },
      secondary: {
        DEFAULT: 'var(--rjopau-colors-secondary500)',
        100: 'var(--rjopau-colors-secondary100)',
        200: 'var(--rjopau-colors-secondary200)',
        300: 'var(--rjopau-colors-secondary300)',
        400: 'var(--rjopau-colors-secondary400)',
        500: 'var(--rjopau-colors-secondary500)',
        600: 'var(--rjopau-colors-secondary600)',
        700: 'var(--rjopau-colors-secondary700)',
        800: 'var(--rjopau-colors-secondary800)',
        900: 'var(--rjopau-colors-secondary900)',
        text: 'var(--rjopau-colors-secondaryText)'
      },
      tertiary: {
        DEFAULT: 'var(--rjopau-colors-tertiary500)',
        100: 'var(--rjopau-colors-tertiary100)',
        200: 'var(--rjopau-colors-tertiary200)',
        300: 'var(--rjopau-colors-tertiary300)',
        400: 'var(--rjopau-colors-tertiary400)',
        500: 'var(--rjopau-colors-tertiary500)',
        600: 'var(--rjopau-colors-tertiary600)',
        700: 'var(--rjopau-colors-tertiary700)',
        800: 'var(--rjopau-colors-tertiary800)',
        900: 'var(--rjopau-colors-tertiary900)',
        text: 'var(--rjopau-colors-tertiaryText)'
      },
      blue: {
        DEFAULT: 'var(--rjopau-colors-blue500)',
        100: 'var(--rjopau-colors-blue100)',
        200: 'var(--rjopau-colors-blue200)',
        300: 'var(--rjopau-colors-blue300)',
        400: 'var(--rjopau-colors-blue400)',
        500: 'var(--rjopau-colors-blue500)',
        600: 'var(--rjopau-colors-blue600)',
        700: 'var(--rjopau-colors-blue700)',
        800: 'var(--rjopau-colors-blue800)',
        900: 'var(--rjopau-colors-blue900)'
      },
      green: {
        DEFAULT: 'var(--rjopau-colors-green500)',
        100: 'var(--rjopau-colors-green100)',
        200: 'var(--rjopau-colors-green200)',
        300: 'var(--rjopau-colors-green300)',
        400: 'var(--rjopau-colors-green400)',
        500: 'var(--rjopau-colors-green500)',
        600: 'var(--rjopau-colors-green600)',
        700: 'var(--rjopau-colors-green700)',
        800: 'var(--rjopau-colors-green800)',
        900: 'var(--rjopau-colors-green900)'
      },
      yellow: {
        DEFAULT: 'var(--rjopau-colors-yellow500)',
        100: 'var(--rjopau-colors-yellow100)',
        200: 'var(--rjopau-colors-yellow200)',
        300: 'var(--rjopau-colors-yellow300)',
        400: 'var(--rjopau-colors-yellow400)',
        500: 'var(--rjopau-colors-yellow500)',
        600: 'var(--rjopau-colors-yellow600)',
        700: 'var(--rjopau-colors-yellow700)',
        800: 'var(--rjopau-colors-yellow800)',
        900: 'var(--rjopau-colors-yellow900)'
      },
      red: {
        DEFAULT: 'var(--rjopau-colors-red500)',
        100: 'var(--rjopau-colors-red100)',
        200: 'var(--rjopau-colors-red200)',
        300: 'var(--rjopau-colors-red300)',
        400: 'var(--rjopau-colors-red400)',
        500: 'var(--rjopau-colors-red500)',
        600: 'var(--rjopau-colors-red600)',
        700: 'var(--rjopau-colors-red700)',
        800: 'var(--rjopau-colors-red800)',
        900: 'var(--rjopau-colors-red900)'
      },
      gray: {
        DEFAULT: 'var(--rjopau-colors-gray500)',
        100: 'var(--rjopau-colors-gray100)',
        200: 'var(--rjopau-colors-gray200)',
        300: 'var(--rjopau-colors-gray300)',
        400: 'var(--rjopau-colors-gray400)',
        500: 'var(--rjopau-colors-gray500)',
        600: 'var(--rjopau-colors-gray600)',
        700: 'var(--rjopau-colors-gray700)',
        800: 'var(--rjopau-colors-gray800)',
        900: 'var(--rjopau-colors-gray900)'
      },
      dark: {
        DEFAULT: 'var(--rjopau-colors-dark500)',
        100: 'var(--rjopau-colors-dark100)',
        200: 'var(--rjopau-colors-dark200)',
        300: 'var(--rjopau-colors-dark300)',
        400: 'var(--rjopau-colors-dark400)',
        500: 'var(--rjopau-colors-dark500)',
        600: 'var(--rjopau-colors-dark600)',
        700: 'var(--rjopau-colors-dark700)',
        800: 'var(--rjopau-colors-dark800)',
        900: 'var(--rjopau-colors-dark900)'
      },
      text: 'var(--rjopau-colors-text)',
      background: {
        DEFAULT: 'var(--rjopau-colors-background)',
        contrast: 'var(--rjopau-colors-backgroundContrast)'
      },
      input: 'var(--rjopau-colors-input)',
      placeholder: 'var(--rjopau-colors-placeholder)',
      disabled: 'var(--rjopau-colors-disabled)',
      border: {
        DEFAULT: 'var(--rjopau-colors-border)'
      }
    },
    extend: {
      spacing: {
        0: 'var(--rjopau-space-0)',
        xs: 'var(--rjopau-space-xs)',
        sm: 'var(--rjopau-space-sm)',
        md: 'var(--rjopau-space-md)',
        lg: 'var(--rjopau-space-lg)',
        xl: 'var(--rjopau-space-xl)',
        '2xl': 'var(--rjopau-space-2xl)',
        '3xl': 'var(--rjopau-space-3xl)',
        '4xl': 'var(--rjopau-space-4xl)',
        '5xl': 'var(--rjopau-space-5xl)',
        '6xl': 'var(--rjopau-space-6xl)',
        '7xl': 'var(--rjopau-space-7xl)',
        '8xl': 'var(--rjopau-space-8xl)',
        '9xl': 'var(--rjopau-space-9xl)',
        min: 'var(--rjopau-space-min)',
        max: 'var(--rjopau-space-max)',
        fit: 'var(--rjopau-space-fit)',
        screen: 'var(--rjopau-space-screen)',
        full: 'var(--rjopau-space-full)',
        px: 'var(--rjopau-space-px)',
        1: 'var(--rjopau-space-1)',
        2: 'var(--rjopau-space-2)',
        3: 'var(--rjopau-space-3)',
        4: 'var(--rjopau-space-4)',
        5: 'var(--rjopau-space-5)',
        6: 'var(--rjopau-space-6)',
        7: 'var(--rjopau-space-7)',
        8: 'var(--rjopau-space-8)',
        9: 'var(--rjopau-space-9)',
        10: 'var(--rjopau-space-10)',
        11: 'var(--rjopau-space-11)',
        12: 'var(--rjopau-space-12)',
        13: 'var(--rjopau-space-13)',
        14: 'var(--rjopau-space-14)',
        15: 'var(--rjopau-space-15)',
        16: 'var(--rjopau-space-16)',
        17: 'var(--rjopau-space-17)',
        18: 'var(--rjopau-space-18)',
        20: 'var(--rjopau-space-20)',
        24: 'var(--rjopau-space-24)',
        28: 'var(--rjopau-space-28)',
        32: 'var(--rjopau-space-32)',
        36: 'var(--rjopau-space-36)',
        40: 'var(--rjopau-space-40)',
        44: 'var(--rjopau-space-44)',
        48: 'var(--rjopau-space-48)',
        52: 'var(--rjopau-space-52)',
        56: 'var(--rjopau-space-56)',
        60: 'var(--rjopau-space-60)',
        64: 'var(--rjopau-space-64)',
        72: 'var(--rjopau-space-72)',
        80: 'var(--rjopau-space-80)',
        96: 'var(--rjopau-space-96)'
      },
      fontSize: {
        xs: 'var(--rjopau-fontSizes-xs)',
        sm: 'var(--rjopau-fontSizes-sm)',
        base: 'var(--rjopau-fontSizes-base)',
        md: 'var(--rjopau-fontSizes-md)',
        lg: 'var(--rjopau-fontSizes-lg)',
        xl: 'var(--rjopau-fontSizes-xl)',
        '2xl': 'var(--rjopau-fontSizes-2xl)',
        '3xl': 'var(--rjopau-fontSizes-3xl)',
        '4xl': 'var(--rjopau-fontSizes-4xl)',
        '5xl': 'var(--rjopau-fontSizes-5xl)',
        '6xl': 'var(--rjopau-fontSizes-6xl)',
        '7xl': 'var(--rjopau-fontSizes-7xl)',
        '8xl': 'var(--rjopau-fontSizes-8xl)',
        '9xl': 'var(--rjopau-fontSizes-9xl)'
      },
      fontFamily: {
        base: 'var(--rjopau-fonts-base)',
        code: 'var(--rjopau-fonts-code)'
      },
      fontWeight: {
        hairline: 'var(--rjopau-fontWeights-hairline)',
        thin: 'var(--rjopau-fontWeights-thin)',
        light: 'var(--rjopau-fontWeights-light)',
        normal: 'var(--rjopau-fontWeights-normal)',
        medium: 'var(--rjopau-fontWeights-medium)',
        semibold: 'var(--rjopau-fontWeights-semibold)',
        bold: 'var(--rjopau-fontWeights-bold)',
        extrabold: 'var(--rjopau-fontWeights-extrabold)',
        black: 'var(--rjopau-fontWeights-black)'
      },
      lineHeight: {
        xs: 'var(--rjopau-lineHeights-xs)',
        sm: 'var(--rjopau-lineHeights-sm)',
        base: 'var(--rjopau-lineHeights-base)',
        md: 'var(--rjopau-lineHeights-md)',
        lg: 'var(--rjopau-lineHeights-lg)',
        xl: 'var(--rjopau-lineHeights-xl)',
        '2xl': 'var(--rjopau-lineHeights-2xl)',
        '3xl': 'var(--rjopau-lineHeights-3xl)',
        '4xl': 'var(--rjopau-lineHeights-4xl)',
        '5xl': 'var(--rjopau-lineHeights-5xl)',
        '6xl': 'var(--rjopau-lineHeights-6xl)',
        '7xl': 'var(--rjopau-lineHeights-7xl)',
        '8xl': 'var(--rjopau-lineHeights-8xl)',
        '9xl': 'var(--rjopau-lineHeights-9xl)'
      },
      letterSpacing: {
        tighter: 'var(--rjopau-letterSpacings-tighter)',
        tight: 'var(--rjopau-letterSpacings-tight)',
        normal: 'var(--rjopau-letterSpacings-normal)',
        wide: 'var(--rjopau-letterSpacings-wide)',
        wider: 'var(--rjopau-letterSpacings-wider)',
        widest: 'var(--rjopau-letterSpacings-widest)'
      },
      opacity: {
        0: 'var(--rjopau-opacity-0)',
        20: 'var(--rjopau-opacity-20)',
        40: 'var(--rjopau-opacity-40)',
        60: 'var(--rjopau-opacity-60)',
        80: 'var(--rjopau-opacity-80)',
        100: 'var(--rjopau-opacity-100)'
      },
      borderWidth: {
        light: 'var(--rjopau-borderWidths-light)',
        normal: 'var(--rjopau-borderWidths-normal)',
        bold: 'var(--rjopau-borderWidths-bold)',
        extrabold: 'var(--rjopau-borderWidths-extraBold)',
        black: 'var(--rjopau-borderWidths-black)'
      },
      borderRadius: {
        none: 'var(--rjopau-radii-none)',
        xs: 'var(--rjopau-radii-xs)',
        sm: 'var(--rjopau-radii-sm)',
        base: 'var(--rjopau-radii-base)',
        md: 'var(--rjopau-radii-md)',
        lg: 'var(--rjopau-radii-lg)',
        xl: 'var(--rjopau-radii-xl)',
        '2xl': 'var(--rjopau-radii-2xl)',
        '3xl': 'var(--rjopau-radii-3xl)',
        squared: 'var(--rjopau-radii-squared)',
        rounded: 'var(--rjopau-radii-rounded)',
        pill: 'var(--rjopau-radii-pill)'
      },
      boxShadow: {
        DEFAULT: 'var(--rjopau-shadows-boxShadow)'
      },
      zIndex: {
        hide: 'var(--rjopau-zIndices-hide)',
        auto: 'var(--rjopau-zIndices-auto)',
        base: 'var(--rjopau-zIndices-base)',
        docked: 'var(--rjopau-zIndices-docked)',
        dropdown: 'var(--rjopau-zIndices-dropdown)',
        sticky: 'var(--rjopau-zIndices-sticky)',
        banner: 'var(--rjopau-zIndices-banner)',
        overlay: 'var(--rjopau-zIndices-overlay)',
        modal: 'var(--rjopau-zIndices-modal)',
        popover: 'var(--rjopau-zIndices-popover)',
        skipLink: 'var(--rjopau-zIndices-skipLink)',
        toast: 'var(--rjopau-zIndices-toast)',
        tooltip: 'var(--rjopau-zIndices-tooltip)'
      },
      animation: {
        default: 'var(--rjopau-transitions-default)',
        button: 'var(--rjopau-transitions-button)'
      }
    }
  },
  plugins: [require('@tailwindcss/line-clamp'), require('@tailwindcss/forms')]
};
